# dependabot.yml

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"

    # Assign reviewers to pull requests
    reviewers:
      - "theoneand33"

    # Add labels to pull requests for better organization
    labels:
      - "dependencies"
