name: bun
on: push
permissions:
  id-token: write
  pages: write
jobs:
  build:
    name: Build with bun and publish to github pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
        
      - name: Ensure dist directory exists
        run: |
          if [ ! -d dist ]; then
            echo "dist directory does not exist after build!"
            exit 1
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Replace 'dist' with the actual output directory of your build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
